version: '3.1'

services:

  rds.fundr.local:
    container_name: rds.fundr.local
    image: postgres:14.2
    restart: always
    ports:
      - '${RDS_PORT}:5432'
    environment:
      POSTGRES_DB: ${RDS_DATABASE}
      POSTGRES_USER: ${RDS_USER}
      POSTGRES_PASSWORD: ${RDS_PASSWORD}